notifications:
    email: false

language:
  - objective-c # enabling osx
  - cpp

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

before_install: tools/travis_before_install.sh

install: tools/travis_install.sh

script: tools/travis_script.sh
